[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parsikit"
version = "3.2.0"
authors = [
    { name = "Ali Kamrani", email = "kamrani.exe@gmail.com" }
]
description = "A production-grade pure Python library for Persian data infrastructure."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: Persian",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.setuptools]
packages = ["parsikit"]